# Generated by Django 4.2 on 2024-08-29 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("record", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="record",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
            },
        ),
    ]
